### ISSUE TITLE
detailed parameters discriptions on timegrid3 and timegrid4? 

### ISSUE THREAD

**Issue by jojogh** [montrixdev/mxdevtool-python#4]
hi, I noticed that you recreated the timegrid class, and what the detailed paremeters discriptions on both class init, say  frequency_month,and frequency_day? 
timegrid3 = mx.TimeGrid(refDate=ref_date, maxYear=10, frequency='endofmonth')
timegrid4 = mx.TimeGrid(refDate=ref_date, maxYear=10, frequency='custom', frequency_month=8, frequency_day=10)

what the meaning on frequency_month=8, frequency_day=10? and what is the different if  frequency_month=1, frequency_day=1?

**Comment by montrixdev** [comment]
hi, it was a bug. frequency='custom' should be frequency_type='annual'.
i tried to fix day or month, while date is rooping using frequency_type( month, quarter, semiannual, annual ).
frequency_month is only used that frequency_type is 'annual'. 
frequency_day is only used that frequency_type is ( month, quarter, semiannual, annual ).
i write samples of timegrid on "run_test_etc.py"
thank you.

**Comment by jojogh** [comment]
ok,sure. BTW, when will the Linux version be released, seems it is not distributed to pip channel?

**Comment by montrixdev** [comment]
hi, the Linux version is released on 0.8.32.1 now. you can use pip channel.
thank you.

**Comment by jojogh** [comment]
ok thanks i like your project
