### ISSUE TITLE
when I used pip to install mxdevtool-python in my windows 10, when I import the project, I met the following error. what is the problem, and how to fix it? Thanks

### ISSUE THREAD

**Issue by jojogh** [montrixdev/mxdevtool-python#5]
import mxdevtool as mx
  File "E:\PyEnv\esgproEnv\lib\site-packages\mxdevtool\__init__.py", line 7, in <module>
    from .mxdevtool import *
  File "E:\PyEnv\esgproEnv\lib\site-packages\mxdevtool\mxdevtool.py", line 13, in <module>
    from . import _mxdevtool
ImportError: DLL load failed: The specified module could not be found.

**Comment by jojogh** [comment]
I thought it is a VC++ version error, could u tell me what version of VC++ running environment you are using?

**Comment by montrixdev** [comment]
hi, i use Visual C++ 2019, and build tool versions are v140, v142.
can you check [Microsoft Visual C++ 2015-2019 Redistributable(x64)](https://aka.ms/vs/16/release/vc_redist.x64.exe)? [Page Link](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0)
i check to execute "import mxdevtool" after uninstall it. so same error is occured as you see.
i install again it. "DLL load failed" error is disappeared.

**Comment by jojogh** [comment]
Let me try! Thanks!

MontrixDev <notifications@github.com> 于2021年1月26日周二 下午8:31写道：
