### ISSUE TITLE
correlation

### ISSUE THREAD

**Issue by jojogh** [montrixdev/mxdevtool-python#6]
I noticed that when generating the scenario by multi-assets, you consider the correlations. But, seems that the correlation matrix is generated by mx.IdentityMatrix(), and this one seems not to be implemented? Right?

BTW, if you considered the correlation matrix, what method will be used to calibrate the corr matrix? 

Thanks!

**Comment by montrixdev** [comment]
Hi jojogh, 
a sample correlation matrix input is considered after make mx.IdentityMatrix(). 

corrMatrix = mx.IdentityMatrix(2)
corrMatrix[1][0] = 0.5
corrMatrix[0][1] = 0.5

this setting is required to calibrate first as you comment.
i write a script for calibrating by historical data. you can check "correlation_test" method  in "run_test_etc.py".
i think other calibration methods like EWMA or factor model should be implemented.
thank you for comment.

**Comment by jojogh** [comment]
many thanks
