### ISSUE TITLE
CIR1F model sigma value range seems can not be larger than 0.1?

### ISSUE THREAD

**Issue by jojogh** [montrixdev/mxdevtool-python#7]
hi, I have tested the CIR1F model, seems the sigma value range can not be larger than 0.1, if set to 0.3, the error occur. 
cir1f = xen.CIR1F('cir1f', r0=0.02, alpha=0.1, longterm=0.042, sigma=0.03)

Is that correct?

Thanks.

**Comment by minikie** [comment]
hi, cir model has a condition that avoids the possibility of negative interest rates.
that is correct condition. 
can you check following [wiki-link](https://en.wikipedia.org/wiki/Cox%E2%80%93Ingersoll%E2%80%93Ross_model)?

- restriction calc
2ab >= sigma^2
2 * 0.1 * 0.042 < 0.1^2
0.0084 < 0.01 is not valid for inequality

thanks.

**Comment by montrixdev** [comment]
hi, cir model has a condition to avoids the possibility of negative interest rates.
that is correct condition. can you check a [wiki-link](https://en.wikipedia.org/wiki/Cox%E2%80%93Ingersoll%E2%80%93Ross_model)?

* restriction inequality calc
2ab >= sigma^2
2 * 0.1 * 0.042 < 0.1^2
0.0084 < 0.01 is not valid for inequality

thanks.

**Comment by jojogh** [comment]
oh, my fault, many thanks!
