### ISSUE TITLE
no support mac platform

### ISSUE THREAD

**Issue by 57ggfk** [montrixdev/mxdevtool-python#8]
no a distribution for darwin version!

**Comment by montrixdev** [comment]
hi~ 
i don't have a experience and a mechine for mac.
it is a quite complicate setting using kvm or docker without mac mechine.
i will check a development for mac.
thanks for a comment.

**Comment by montrixdev** [comment]
hi, the macOS version is released on 0.8.35.3 now ( python version 3.8, 3.9 only ). you can use pip channel.
thank you.
