### ISSUE TITLE
How can I install mxdevtool-python in ARM cpu computer?

### ISSUE THREAD

**Issue by jojogh** [montrixdev/mxdevtool-python#9]
How can I install mxdevtool-python in ARM cpu computer? Need to build the whole from scratch in an ARM computer env? Will you release an arm version?

**Comment by montrixdev** [comment]
Hi, an ARM version is only available on macos. I will follow up ARM version(aarch64 <- is that right?) for linux next release.
Windows ARM version is not planned at now.

Thanks!

**Comment by montrixdev** [comment]
0.8.38.0 version support linux(aarch64) now. 

Thanks!

**Comment by jojogh** [comment]
many thanks
